// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/funinthecloud/protosource"
	"github.com/funinthecloud/protosource-auth/authz/httpauthz"
	"github.com/funinthecloud/protosource/authz"
	"github.com/funinthecloud/protosource/authz/allowall"
	"github.com/funinthecloud/protosource/serializers/protobinaryserializer"
	"github.com/funinthecloud/protosource/stores/dynamodbstore"
	"github.com/funinthecloud/todoapp/backend-lambda/gen/showcase/app/todolist/v1"
	"github.com/funinthecloud/todoapp/backend-lambda/gen/showcase/app/todolist/v1/todolistv1dynamodb"
	"os"
)

// Injectors from wire.go:

// InitializeRouter wires all dependencies and returns a configured router.
func InitializeRouter(client *dynamodb.Client, eventsTable dynamodbstore.EventsTableName, aggregatesTable dynamodbstore.AggregatesTableName) (*protosource.Router, error) {
	store := dynamodbstore.ProvideOpaqueStore(client, aggregatesTable)
	dynamoDBStore, err := dynamodbstore.ProvideStore(client, store, eventsTable)
	if err != nil {
		return nil, err
	}
	serializer := protobinaryserializer.NewSerializer()
	repository := todolistv1dynamodb.ProvideRepository(dynamoDBStore, serializer)
	todoListClient := todolistv1.NewTodoListClient(store)
	authorizer := provideAuthorizer()
	handler := todolistv1.NewHandler(repository, todoListClient, authorizer)
	router := provideRouter(handler)
	return router, nil
}

// wire.go:

func provideRouter(
	todolistHandler *todolistv1.Handler,
) *protosource.Router {
	return protosource.NewRouter(todolistHandler)
}

// provideAuthorizer returns an httpauthz.Authorizer pointing at the
// protosource-auth service URL supplied by PROTOSOURCE_AUTH_URL, or
// allowall.Authorizer{} when the env var is empty. Production lambda
// deployments set PROTOSOURCE_AUTH_URL to the auth service's endpoint.
func provideAuthorizer() authz.Authorizer {
	if url := os.Getenv("PROTOSOURCE_AUTH_URL"); url != "" {
		return httpauthz.New(url)
	}
	return allowall.Authorizer{}
}
