// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/funinthecloud/protosource"
	"github.com/funinthecloud/protosource/authz/allowall"
	"github.com/funinthecloud/protosource/serializers/protobinaryserializer"
	"github.com/funinthecloud/protosource/stores/dynamodbstore"
	"github.com/funinthecloud/todoapp/backend-lambda/gen/showcase/app/todolist/v1"
)

// Injectors from wire.go:

// InitializeRouter wires all dependencies and returns a configured router.
func InitializeRouter(client *dynamodb.Client, eventsTable dynamodbstore.EventsTableName, aggregatesTable dynamodbstore.AggregatesTableName) (*protosource.Router, error) {
	store := dynamodbstore.ProvideOpaqueStore(client, aggregatesTable)
	dynamoDBStore, err := dynamodbstore.ProvideStore(client, store, eventsTable)
	if err != nil {
		return nil, err
	}
	serializer := protobinaryserializer.NewSerializer()
	repository := todolistv1.ProvideRepository(dynamoDBStore, serializer)
	todoListClient := todolistv1.NewTodoListClient(store)
	authorizer := allowall.Provide()
	handler := todolistv1.NewHandler(repository, todoListClient, authorizer)
	router := provideRouter(handler)
	return router, nil
}

// wire.go:

func provideRouter(
	todolistHandler *todolistv1.Handler,
) *protosource.Router {
	return protosource.NewRouter(todolistHandler)
}
