// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/funinthecloud/protosource"
	"github.com/funinthecloud/protosource/authz"
	"github.com/funinthecloud/protosource/serializers/protobinaryserializer"
	"github.com/funinthecloud/protosource/stores/boltdbstore"
	"github.com/funinthecloud/todoapp/backend-bolt/gen/showcase/app/todolist/v1"
)

// Injectors from wire.go:

func InitializeRepository() (*protosource.Repository, error) {
	boltDBStore, err := provideStore()
	if err != nil {
		return nil, err
	}
	serializer := protobinaryserializer.NewSerializer()
	repository := provideRepository(boltDBStore, serializer)
	return repository, nil
}

func InitializeHandler(repo *protosource.Repository, authorizer authz.Authorizer) *todolistv1.Handler {
	handler := provideHandler(repo, authorizer)
	return handler
}

// wire.go:

func provideStore() (*boltdbstore.BoltDBStore, error) {
	return boltdbstore.New("data", "todolist")
}

func provideRepository(store *boltdbstore.BoltDBStore, serializer *protobinaryserializer.Serializer) *protosource.Repository {
	return todolistv1.NewRepository(store, serializer)
}

func provideHandler(repo *protosource.Repository, authorizer authz.Authorizer) *todolistv1.Handler {
	return todolistv1.NewHandler(repo, nil, authorizer)
}
