// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/funinthecloud/protosource"
	"github.com/funinthecloud/protosource-showcase/backend/gen/showcase/app/todolist/v1"
	"github.com/funinthecloud/protosource/serializers/protobinaryserializer"
	"github.com/funinthecloud/protosource/stores/memorystore"
)

// Injectors from wire.go:

func InitializeRepository() *protosource.Repository {
	memoryStore := provideStore()
	serializer := protobinaryserializer.NewSerializer()
	repository := provideRepository(memoryStore, serializer)
	return repository
}

func InitializeHandler(repo *protosource.Repository) *todolistv1.Handler {
	handler := provideHandler(repo)
	return handler
}

// wire.go:

func provideStore() *memorystore.MemoryStore {
	return memorystore.New(todolistv1.SnapshotEveryNEvents)
}

func provideRepository(store *memorystore.MemoryStore, serializer *protobinaryserializer.Serializer) *protosource.Repository {
	return todolistv1.NewRepository(store, serializer)
}

func provideHandler(repo *protosource.Repository) *todolistv1.Handler {
	return todolistv1.NewHandler(repo, nil)
}
